dist: xenial
language: node_js
node_js:
  - 12
services:
  - mysql
before_script:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version
  - mysql -e 'CREATE DATABASE yocto_erp_test;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('12345678') WHERE user='root';\nupdate user set plugin='mysql_native_password';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root --password="" < sql/init.sql
