dist: xenial
language: node_js
node_js:
  - 12
services:
  - mysql
before_script:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version
  - mysql -u root --password="" < sql/init.sql
env:
  - DB_HOST = "127.0.0.1"
  - DB_USERNAME = "root"
  - DB_PASSWORD = ""
  - DB_NAME = "yocto_erp_test"
  - WEB_URL = "http://localhost:4201"
  - NODE_ENV = "test"
