site_name: Yocto BankEnd Api
repo_url: https://github.com/yocto-erp/backend
repo_name: 'GitHub'
copyright: 'MIT'
theme: readthedocs
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Inventory:
    - 'Summary': './inventory/summary.md'
    - 'Warehouse In': './inventory/in.md'
    - 'Warehouse Out': './inventory/out.md'
